## software stack, will work out of the box if within the supplied docker container
Rbin: R
STAR: STAR

repo_path: '.'

## run limits
nthreads: 50
max_mem_mb: 20000 ## these are megabytes

# downsampled: 50000000 # or 0

## cell filtering
# soloCellFilter: "EmptyDrops_CR" # None, TopCells, CellRanger2.2
soloCellFilter: "EmptyDrops_CR" # "CellRanger2.2" # None, TopCells, CellRanger2.2

## multimappers
soloMultiMappers: "Unique" # Uniform, Rescue , PropUnique, EM

## extra STARsolo arguments
extraStarSoloArgs: "--soloStrand Unstranded"

## full, absolute path where outputs will be generated at
working_dir: /home/imallona/noname/test_run/


gtf_origin: "gencode"
# https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M35/gencode.vM35.primary_assembly.annotation.gtf.gz
# caution uncompressed
gtf: /home/imallona/src/noname/data/gencode.vM35.primary_assembly.annotation.gtf
# https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M35/GRCm39.primary_assembly.genome.fa.gz
# caution uncompressed
genome: /home/imallona/src/noname/data/GRCm39.primary_assembly.genome.fa
# https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M35/gencode.vM35.pc_transcripts.fa.gz
# caution compressed
transcriptome: /home/imallona/src/noname/data/gencode.vM35.pc_transcripts.fa.gz

# readlength is 71, but something is odd with cDNA reads - reducing
sjdbOverhang: 50

# aligner: ['starsolo']
aligner: ['starsolo', 'kallisto', 'alevin']
      
samples:
  - name: example_50M
    uses:
      # cb_umi_fq: /home/gmoro/concatenated_bd_demo/WTA_SMK_R1.fastq.gz
      # cdna_fq: /home/gmoro/concatenated_bd_demo/WTA_SMK_R2.fastq.gz
      cb_umi_fq: /home/gmoro/concatenated_bd_demo/combined_50M_R1_WTA_SMK.fastq.gz
      cdna_fq: /home/gmoro/concatenated_bd_demo/combined_50M_R2_WTA_SMK.fastq.gz
      whitelist: 384x3
      species: 'human'

  # this doesn't work, the named pipe is not "seekable" for cutadapt
  # cd /home/imallona/tmp//bdrhapsody_demo/12WTA-ABC-SMK-EB-5kJRT/
  # mkfifo r1.fq.gz
  # mkfifo r2.fq.gz
  # cat 12SMK_S1_L432_R1_001.fastq.gz 12WTA_S1_L432_R1_001.fastq.gz > r1.fq.gz &
  # cat 12SMK_S1_L432_R2_001.fastq.gz 12WTA_S1_L432_R2_001.fastq.gz > r2.fq.gz &
  # concatenate physically instead, with cat
  
  - name: example_fifo
    uses:
      cb_umi_fq: "/home/imallona/tmp/bdrhapsody_demo/12WTA-ABC-SMK-EB-5kJRT/r1.fq.gz"
      cdna_fq: "/home/imallona/tmp/bdrhapsody_demo/12WTA-ABC-SMK-EB-5kJRT/r2.fq.gz"
      whitelist: 384x3
      species: 'human'
