## simulate: True generates fake data and runs the pipeline
simulate: True

## software stack, will work out of the box if within the supplied docker container
Rbin: R
STAR: STAR

repo_path: '.'

## run limits
nthreads: 2
max_mem_mb: 20000 ## these are megabytes

## full or relative path to the `root` of the rock_roi_method cloned repository
# rock_method_path: "."

## full or relative path where outputs will be generated at
working_dir: work

# https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M35/gencode.vM35.primary_assembly.annotation.gtf.gz
# caution uncompressed
gtf: data/gencode.vM35.primary_assembly.annotation.gtf
# https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M35/GRCm39.primary_assembly.genome.fa.gz
# caution uncompressed
genome: data/GRCm39.primary_assembly.genome.fa

sjdbOverhang: 61

samples:
  - name: pbmc
    uses:
      cb_umi_fq: data/325411_1-Unmod_WTA_S1_R1_001_downsampled.fastq.gz
      cdna_fq: data/325411_1-Unmod_WTA_S1_R1_001_downsampled.fastq.gz
      whitelist: 384x3
