simulate: True
gtf: ../data/genome.gtf
genome: ../data/genome.fa
Rbin: R
STAR: STAR
fastq_path: ../data
metadata: ../data/metadata.txt
nthreads: 2
per_task_max_nthreads: 5
per_task_max_mem:  1038822112
samples:
  - name: simulated
    uses:
      cb_umi_fq: ../data/simulated/r1.fq.gz
      cdna_fq: ../data/simulated/r2.fq.gz
      whitelist: 96x3
      expected_cells: 1
  - name: simulated2
    uses:
      cb_umi_fq: ../data/simulated2/r1.fq.gz
      cdna_fq: ../data/simulated2/r2.fq.gz
      whitelist: 96x3
      expected_cells: 2
