simulate: True
gtf: ../data/genome.gtf
genome: ../data/genome.fa
Rbin: R
STAR: STAR
fastq_path: ../data
metadata: ../data/metadata.txt
nthreads: 20
per_task_max_nthreads: 5
samples:
  - name: simulated
    uses:
      cb_umi_fq: ../data/simulated/r1.fq.gz
      cdna_fq: ../data/simulated/r2.fq.gz
      whitelist: 90x3
      expected_cells: 10000
  - name: simulated2
    uses:
      cb_umi_fq: ../data/simulated2/r1.fq.gz
      cdna_fq: ../data/simulated2/r2.fq.gz
      whitelist: 90x3
      expected_cells: 2
