## simulate: True generates fake data and runs the pipeline
simulate: True

## where outputs will be generated at
working_dir: /home/imallona/tmp/snmk

## software stack, will work out of the box if within the supplied docker container
Rbin: R
STAR: STAR

## run limits
nthreads: 2
per_task_max_nthreads: 5
per_task_max_mem:  1038822112

## to fill if `simulate : False`
## if `simulate: True` then all config below this line will be replaced by
##   hardcoded values (within the Snakefile)
gtf: /home/imallona/tmp/snmk/data/genome.gtf
genome: /home/imallona/tmp/snmk/data/genome.fa

## GTF `source` field identifying on-target rock- or roi- features
capture_gtf_column_2_pattern : 'captured'

samples:
  - name: simulated
    uses:
      cb_umi_fq: /home/imallona/tmp/snmk/data/simulated/r1.fq.gz
      cdna_fq: /home/imallona/tmp/snmk/data/simulated/r2.fq.gz
      whitelist: 96x3
      expected_cells: 500
  - name: simulated2
    uses:
      cb_umi_fq: /home/imallona/tmp/snmk/data/simulated/r1.fq.gz
      cdna_fq: /home/imallona/tmp/snmk/data/simulated/r2.fq.gz
      whitelist: 96x3
      expected_cells: 500
